#apiVersion: v1
#kind: Service
#metadata:
#  name: service-2-service
#spec:
#  selector:
#    app: service-2
#  ports:
#    - protocol: TCP
#      port: 81
#      targetPort: 8081
#  type: LoadBalancer  
  
  
# Spring Boot Service 2 Service
apiVersion: v1
kind: Service
metadata:
  name: service-2-service
spec:
  selector:
    app: service-2
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
  type: LoadBalancer  