apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: 539247471581.dkr.ecr.eu-north-1.amazonaws.com/ecr/test:aap2
          ports:
            - containerPort: 8081