#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: kafka-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: kafka
#  template:
#    metadata:
#      labels:
#        app: kafka
#    spec:
#      containers:
#        - name: kafka
#          image: wurstmeister/kafka:latest  # Or your custom Kafka image
#          ports:
#            - containerPort: 9092
#          env:
#            - name: KAFKA_ADVERTISED_LISTENERS
#              value: "PLAINTEXT://kafka-service:9092"
#            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
#              value: "PLAINTEXT"
#            - name: KAFKA_LISTENER_PORT
#              value: "9092"
#            - name: KAFKA_ZOOKEEPER_CONNECT
#              value: "zookeeper:2181"
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-service
#spec:
#  selector:
#    app: kafka
#  ports:
#    - protocol: TCP
#      port: 9092
#      targetPort: 9092
#  type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest  # Or your custom Kafka image
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: "PLAINTEXT"
            - name: KAFKA_LISTENER_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
