apiVersion: v1
kind: Service
metadata:
  name: service-1-service
spec:
  selector:
    app: service-1
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8081
  type: LoadBalancer    
      