name: Deploy to EKS (Multi-Service)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      # Build and Push Service 1
      - name: Build and Push Service 1
        run: |
          docker build -t app1 ./Project
          docker tag app1:latest ${{ secrets.ECR_REPOSITORY }}:app1
          docker push ${{ secrets.ECR_REPOSITORY }}:app1

      # Build and Push Service 2
      - name: Build and Push Service 2
        run: |
          docker build -t app2 ./micro2
          docker tag app2:latest ${{ secrets.ECR_REPOSITORY }}:app2
          docker push ${{ secrets.ECR_REPOSITORY }}:app2
  
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      # Deploy Kafka Service (if you need to deploy Kafka within Kubernetes)
      - name: Deploy Kafka Service
        run: |
          kubectl apply -f ./k8s/kafka-deployment.yaml
          kubectl apply -f ./k8s/kafka-service.yaml   curl service-1-service:81/logs/send -X POST -d "Test message" -H "Content-Type: text/plain"

      - name: Deploy to EKS (Service 1)
        run: |
          kubectl apply -f ./Project/k8s/app1-deployment.yaml
          kubectl apply -f ./Project/k8s/app1-service.yaml

      - name: Deploy to EKS (Service 2)
        run: |
          kubectl apply -f ./micro2/k8s/app2-deployment.yaml
          kubectl apply -f ./micro2/k8s/app2-service.yaml
